version: '3'

services:

  app:
    build: .
    volumes:
      - ./src/:/var/www/html
    environment:
      DEBUG: true

  adminer:
    image: adminer
    container_name: mydb-adminer
    networks:
      - frontend
      - backend
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mydb-mariadb
