version: '3'
services:
  db:
    image: mariadb
    container_name: mydb-mariadb
    restart: always
    networks:
      - backend
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: mydb
      MARIADB_USER: mydb
      MARIADB_PASSWORD: mydb

  web:
    build: .
    image: mydb
    container_name: mydb
    restart: always
    networks:
      - backend
      - frontend
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html
    ports:
      - 80:80

  adminer:
    image: adminer
    container_name: mydb-adminer
    restart: always
    networks:
      - backend
      - frontend
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mydb-mariadb

networks:
  backend:
  frontend:
