version: "3"
services:
  db:
    hostname: mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - backend
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydb
      MYSQL_PASSWORD: mydb
    ports:
      - 3306:3306

  web:
    hostname: php-app
    build:
      context: .
      dockerfile: Dockerfile
    image: php-app
    container_name: php-app
    networks:
      - backend
      - frontend
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html
    ports:
      - 80:80

  phpmyadmin:
    hostname: phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mydb
      MYSQL_PASSWORD: mydb
    networks:
      - backend
      - frontend
    links:
      - db:db
    depends_on:
      - db
    ports:
      - 8080:80

networks:
  backend:
  frontend:
